import { Repeat } from "lucide-react";
import { Badge } from "@/components/ui/badge";

interface RecurringBadgeProps {
  isAutoGenerated?: boolean;
}

export function RecurringBadge({ isAutoGenerated }: RecurringBadgeProps) {
  if (!isAutoGenerated) return null;

  return (
    <Badge 
      variant="secondary" 
      className="gap-1 bg-primary/10 text-primary hover:bg-primary/20"
    >
      <Repeat className="h-3 w-3" />
      <span className="text-xs">Auto</span>
    </Badge>
  );
}
